language: python
python:
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
- 3.7-dev
install:
- pip install .
script:
- pytest
notifications:
  email: false
deploy:
  provider: pypi
  skip_existing: true
  user: benblamey
  password:
    secure: cILY1M7wCmcSw9DjtuImVANaIFyo6FeAJkOMXU57SjXi2GGnKT839PgRLk0eYjtCsqfmrcJdaB59B3Ep1M7ifGhqJyOgyOFNIbySqrDkLQDHzskAPz0diZIDTVu1oVJMGSrQoCjsBAt8FIbv9QNVEfPIWKVYOf3wR+GIRVQbWphLO+/vbgMm9u5dWYGD3KONcRRbnIwv7Gqo37dN6MroT1GnywxU4rEnYMpMRZVnvxMod96zfdLYEAQ4SGMiKwmUCQ+DaRTqIv7/bGAytSIs37aEF0ljucjFv4At6o0biXTTXuNKGLTz6Qh+PsLB5kuPCMtGNvoBvLCZ88wz/WIPj+3O2mW1+j0ZVjuh5JiysjpScoKkQI7BmBsnJobxL4Zos1RMST+1piGGiR8yRg+yAsF8tjKbrAi7ClL+QjJY9ExOa2HNg7XIJgm3VrUmDVeLM8O9Ni1o9z6Vjg8NFn1M6Rxarja+Vr7gRdf/N60LwAnXUVfuAiIGHMgxyJ7iUfxMYSlPDo8PlgVhqP9qk49XitMK2d2N1Xskef3w5X1aEs0lLCPFmwuTMPcxsWM0lTiLw+sQzImKwYgN/sAU5+809X+VSt/GhGIwWupYYWDZDXDNVnXx3z3IFOIm+w3G4scIBCSHgS5dpfKBuuuSeO+0msphdIaLIohDYp29t4087wE=
